version: "3"

services:
  mi-mongo:
    container_name: mi-mongo
    networks:
      mongo-node-net:
        ipv4_address: 172.40.0.10
    volumes:
      - mongo-vol:/data/db
    image: mongo
    expose:
      - "27017"

  mi-node:
    container_name: mi-node
    networks:
      mongo-node-net:
        ipv4_address: 172.40.0.11
      node-nginx-net:
        ipv4_address: 172.80.0.10
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"

  mi-nginx:
    container_name: mi-nginx
    networks:
      node-nginx-net:
        ipv4_address: 172.80.0.11
    ports:
      - "80:80"
    image: nginx

networks:
  mongo-node-net:
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16
  node-nginx-net:
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/16

volumes:
  mongo-vol:
